### PR TITLE
Add github action to build collectd

### PR DESCRIPTION
**Pull request by elfiesmelfie**
Repeats the steps that travis was using for building colelctd

* checks out branch
* installs dependencies
* runs the script commands from travis ( pkg-config, confgure, make)

### CODE REVIEW

**Comment by mrunge** [comment]
Thank you Emma. Can we make the fedora checks non-voting for now? There is clearly some work to do in the code.

**Comment by elfiesmelfie** [comment]
> Thank you Emma. Can we make the fedora checks non-voting for now? There is clearly some work to do in the code.

The settings I have for it SHOULD mean that fedora is skipped.
Looking at the workflow runs from the actions tab, the job seems to be successful, even when the fedora_rawhide task is failed, however the PR status does not match this.
I'll take a look and see if this is expected or not, and worst case, I can move the task to a different workflow, and have the entire workflow marked as optional

**Comment by eero-t** [comment]
Looking at the CI error, `PyEval_InitThreads()` instances should be enclosed in `#if PY_VERSION_HEX < 0x03090000`

See: https://docs.python.org/3/c-api/init.html#c.PyEval_InitThreads

**Comment by elfiesmelfie** [comment]
Moved to: https://github.com/collectd-mirror/collectd/pull/1

**Pull request closed without merging**
